# Generated by Django 2.2.2 on 2022-06-06 14:05

from django.db import migrations, models
import estates.models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=estates.models.upload_location),
        ),
        migrations.AlterField(
            model_name='estatepost',
            name='proof_doc',
            field=models.FileField(blank=True, null=True, upload_to=estates.models.upload_location),
        ),
    ]
